### ISSUE TITLE
Q: Superset Integration?

### ISSUE THREAD

**Issue by graphadvantage** [TwoBitAlchemist/NeoAlchemy#1]
Hi,

This is really nice - I ran across your package looking for a way to integrate Neo4j and Superset, the AirBnB opensource BI package, that runs entirely off of SQLAlchemy plugins.

It has some great viz capabilities, including force-directed graphs.

http://airbnb.io/superset/installation.html

Are you aware of a sqlalchemy-neo4j package?

Thanks

Michael

**Comment by TwoBitAlchemist** [comment]
Hi,

Sorry it's taken me so long to get back to you. I've had some awful illness going around and been out of pocket for several days.

I'm not familiar with any SQLAlchemy/Neo4J crossover packages. That's not to say there aren't any; I just don't know of them. Even this library isn't integrated with SQLAlchemy at all -- I just took inspiration from their ORM setup.

I'm not actively working on this right now (and won't be for a couple of months at least) but if anything in the codebase helps you, feel free to fork it or use what is there.
