### ISSUE TITLE
Executing queries

### ISSUE THREAD

**Issue by jpek-m** [TwoBitAlchemist/NeoAlchemy#3]
I didn't find from your documentation, how a query should be run. I create a query like this:

> query = Match(User).where(User.username=='Risto').return_({'n': 'username'})

but what is recommended way of executing it?

**Comment by TwoBitAlchemist** [comment]
Sorry it took me a bit to get back to this. Just took a new position and I'm moving across the country!

Open a connection to your graph as described [here](https://neoalchemy.readthedocs.io/en/latest/intro.html#connecting-to-a-graph). Then call [query](https://neoalchemy.readthedocs.io/en/latest/schema-classes.html#Graph.query) on the resulting graph object. I'm closing this but you can re-open it if that didn't fully answer your question or you have a follow up.
