### ISSUE TITLE
Current Support Status

### ISSUE THREAD

**Issue by SoundsSerious** [TwoBitAlchemist/NeoAlchemy#7]
Hi,

Love the idea behind this project, would love to know if its ready to be used in an enterprise project? 

I see there hasn't been an issue, or update in some years, are there any features that don't work as intended?

Thanks!

**Comment by TwoBitAlchemist** [comment]
Hi, sorry. This is basically unsupported and unmaintained, although several forks exist (I don't know the status of any). I wrote this several years ago and switched jobs before I really got to take it all the places I wanted it to go, and I don't really have access to the Neo4J enterprise product any more so I haven't put any more work into it.

**Comment by SoundsSerious** [comment]
Thanks for the info 🙏🏻

I ended up going with arangodb because enterprise costs an arm and a leg so I completely understand. 

The tech seems very nice, I’m sure it’s great to use!
